### PR TITLE
To Do List: Add and remove

### PR DESCRIPTION
**Pull request by MPDADDY**
Hello👏
I have added functionality to the To-do list App. Some of the functionalities added are:

1. Tasks can be deleted using a delete button.
2. Tasks can be edited by clicking the task description.
3. Tasks can be marked as complete by clicking the button with the letter 'c' and thereafter deleted at one using the button 'clear all completed'.
4. All changes are saved to the locale storage.

### CODE REVIEW

**Review by OyePriscilla — CHANGES_REQUESTED** [review]
Hi @MPDADDY 👍 👍 👍 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close

## Highlights
Removed all hardcoded items from the tasks array ✔️ 
Implemented a function for adding, deleting and editing task ✔️ 
All changes to the To Do saved in local storage ✔️ 


## Required Changes ♻️

- [ ] Please kindly fix the issue link in the README file that is broken at the moment (**404 error**). Implementing this will make your repo to be more engaging. 👍

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MPDADDY** [comment]
Fixed the change from the previous reviewer.

**Comment by MPDADDY** [comment]
Fixed the change requested by the previous reviewer.

**Review by Reem-lab — APPROVED** [review]
# Hi @MPDADDY, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descrtipive PR⭐
- [ ] Kudos for working on functionality for adding and removing🤩
- [ ] No Linters error ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
